# Site settings
title: Douglas Gusson
email: douglasgusson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog de um desenvolvedor entusiasta de novas tecnologias.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://douglasgusson.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
lang: "pt-br"
disqus:
    shortname: douglasgusson-github-io
plugins:
  - jekyll-feed
  - jekyll-paginate


paginate: 3
paginate_path: "/page:num/"


exclude: ["Gemfile", "Gemfile.lock"]